# Generated by Django 4.0 on 2021-12-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name_client',
            field=models.CharField(default=1, max_length=150, verbose_name='Nome Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
