# Generated by Django 4.0 on 2021-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
    ]
