# Generated by Django 4.0 on 2021-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
