# Generated by Django 4.0 on 2022-01-10 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_product_min_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_min',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade minima'),
        ),
    ]
